version: '3.5'
services:
  flask-app:
    container_name: flask-app
    build: .
    ports:
      - "5000:5000"
    command: main.py
    volumes:
      - .:/src
      - ./tests/reports/:/src/tests/reports
    environment:
      - PYTHONPATH=/src
      - FLASK_ENV=testing
      - APP_SETTINGS=testing
      - FLASK_APP=main.py
    tty: true

  allure-report:
    image: "frankescobar/allure-docker-service"
    container_name: allure-report
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./tests/reports/:/app/allure-results
    depends_on:
      - flask-app

  selenium-hub:
    image:  selenium/hub
    container_name: selenium-hub
    ports:
      - '4444:4444'
    networks:
      - grid
  
  chrome:
    image: selenium/node-chrome
    ports:
      - '5900'
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: '4444'
    depends_on:
      - selenium-hub
    networks:
      - grid
    
  firefox:
    image: selenium/node-firefox
    ports:
      - '5900'
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: '4444'
    depends_on:
      - selenium-hub
    networks:
      - grid

networks:
  grid:
    driver: bridge