version: '3'
services:
  flask-app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    command: main.py
    volumes:
      - .:/src
      - ./tests/reports/:/src/tests/reports
    environment:
      - PYTHONPATH=/src
      - FLASK_ENV=testing
      - APP_SETTINGS=testing
      - FLASK_APP=main.py
    tty: true
  allure-report:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./tests/reports/:/app/allure-results