version: '3'
services:
  flask-app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    command: main.py
    volumes:
      - .:/src
    environment:
      - PYTHONPATH=/src
      - FLASK_ENV=testing
      - APP_SETTINGS=testing
      - FLASK_APP=main.py
    tty: true